CREATE TABLE students AS
   SELECT "7/28/2017 8:46:30" AS time, 42 AS number, "mustard yellow" AS color, "I do what I want." AS seven, 286 as sneeze, "ballet" as expert, "21 Cabbage" as beets, "Image 2" AS image, "unicorn" AS pet, "9/7" AS date, 5 AS smallest UNION
   SELECT "7/28/2017 8:51:21" , 11 , "black"                     , "Choose this option instead.", 1         , "bees"                                                          , "Pea Diddy"                                     , "Image 4", "bunny"                           , "12/25", 8    UNION
   SELECT "7/30/2017 8:52:21" , 42 , "purple"                    , "I do what I want."          , 87658.1277, "growing bonsai"                                                , "Metro' Bloomin (even though he's not a rapper)", "Image 1", "lion"                            , "12/12", 13   UNION
   SELECT "7/30/2017 11:42:29", 9  , "blue"                      , "YOLO!"                      , 60        , "programming"                                                   , "Kendrick Farmar"                               , "Image 1", "dog"                             , "5/25" , 14   UNION
   SELECT "7/30/2017 11:52:24", 25 , "blue"                      , "I do what I want."          , 1         , "happiness"                                                     , "Beets by Dre"                                  , "Image 4", "lion"                            , "9/9"  , 1    UNION
   SELECT "7/30/2017 11:53:51", 6  , "blue"                      , "the number 7"               , 666       , "aerospace"                                                     , "Kendrick Farmar"                               , "Image 3", "penguin"                         , "6/16" , 3    UNION
   SELECT "7/30/2017 11:56:07", 1  , "purple"                    , "Choose this option instead.", 7         , "music production"                                              , "2 Grainz"                                      , "Image 1", "a dog"                           , "3/4"  , 31   UNION
   SELECT "7/30/2017 11:56:59", 13 , "grey"                      , "7"                          , 336       , "surfing"                                                       , "Tyler, the Cultivator"                         , "Image 4", "lionnnn (dk khalid voice)"       , "1/1"  , 1    UNION
   SELECT "7/30/2017 12:13:44", 99 , "white"                     , "the number 7"               , 99        , "being an expert"                                               , "50 cent"                                       , "Image 3", "human"                           , "7/30" , 9    UNION
   SELECT "7/30/2017 12:19:49", 23 , "mint"                      , "Choose this option instead.", 0.5       , "memes"                                                         , "Beets by Dre"                                  , "Image 2", "dropbear"                        , "7/30" , 6    UNION
   SELECT "7/30/2017 12:20:11", 42 , "gold"                      , "the number 7"               , 1         , "spicy memes"                                                   , "The Roots"                                     , "Image 4", "tiger"                           , "4/20" , 6    UNION
   SELECT "7/30/2017 12:25:09", 88 , "navy"                      , "7"                          , 100       , "61a"                                                           , "Kanye Fresh"                                   , "Image 1", "none"                            , "8/10" , 1    UNION
   SELECT "7/30/2017 12:25:52", 4  , "blue"                      , "I'm a rebel."               , 1E+033    , "in being an expert, where is eminem for the next question ?? ?", "Beets by Dre"                                  , "Image 1", "myself"                          , "7/7"  , 26   UNION
   SELECT "7/30/2017 12:28:25", 34 , "navy blue"                 , "7"                          , 200       , "eating food"                                                   , "Pea Diddy"                                     , "Image 1", "corgi"                           , "7/29" , 1    UNION
   SELECT "7/30/2017 12:29:25", 13 , "silver"                    , "7"                          , 12        , "software engineering"                                          , "50 cent"                                       , "Image 1", "cheetah"                         , "12/31", 1    UNION
   SELECT "7/30/2017 12:30:19", 7  , "black"                     , "the number 7"               , 64        , "cs61a"                                                         , "21 Cabbage"                                    , "Image 1", "dragon"                          , "12/30", 7    UNION
   SELECT "7/30/2017 12:31:17", 14 , "blue"                      , "7"                          , 168       , "life"                                                          , "Kanye Fresh"                                   , "Image 1", "cat"                             , "6/1"  , 2    UNION
   SELECT "7/30/2017 12:43:59", 14 , "pink"                      , "You are not the boss of me!", 24        , "sex"                                                           , "Post Melon"                                    , "Image 3", "pikachu"                         , "7/30" , 14   UNION
   SELECT "7/30/2017 12:53:09", 8  , "blue"                      , "the number 7"               , 1000      , "future "                                                       , "Metro' Bloomin (even though he's not a rapper)", "Image 1", "fox"                             , "1/1"  , 7    UNION
   SELECT "7/30/2017 12:56:33", 42 , "pale pink"                 , "the number 7"               , 48        , "what"                                                          , "Tyler, the Cultivator"                         , "Image 1", "kakako"                          , "2/8"  , 39   UNION
   SELECT "7/30/2017 13:10:42", 88 , "navy"                      , "7"                          , 48        , "programming"                                                   , "The Roots"                                     , "Image 1", "eagle"                           , "8/11" , 14   UNION
   SELECT "7/30/2017 13:12:01", 3  , "yellow"                    , "Choose this option instead.", 1         , "dog walking"                                                   , "Tyler, the Cultivator"                         , "Image 1", "dog"                             , "12/12", 8    UNION
   SELECT "7/30/2017 13:41:15", 97 , "red"                       , "Choose this option instead.", 0         , "cs61a"                                                         , "Tyler, the Cultivator"                         , "Image 4", "elephant"                        , "8/6"  , 108  UNION
   SELECT "7/30/2017 13:46:22", 77 , "black"                     , "7"                          , 5         , "positive thinking"                                             , "The Roots"                                     , "Image 1", "lion"                            , "3/3"  , 0    UNION
   SELECT "7/30/2017 13:54:19", 77 , "white"                     , "7"                          , 1         , "data science"                                                  , "Kendrick Farmar"                               , "Image 1", "lion"                            , "8/10" , 1    UNION
   SELECT "7/30/2017 14:02:27", 20 , "yellow"                    , "7"                          , 480       , "designing"                                                     , "Beets by Dre"                                  , "Image 1", "lion"                            , "4/5"  , 1    UNION
   SELECT "7/30/2017 14:48:52", 97 , "ultramarine"               , "7"                          , 24        , "solving problems"                                              , "Kendrick Farmar"                               , "Image 4", "tanuki"                          , "1/23" , 1    UNION
   SELECT "7/30/2017 14:51:23", 34 , "blue"                      , "7"                          , 800       , "computer science"                                              , "50 cent"                                       , "Image 1", "dragon"                          , "3/4"  , 1    UNION
   SELECT "7/30/2017 14:52:41", 27 , "blue"                      , "the number 7"               , 100       , "poon"                                                          , "Kendrick Farmar"                               , "Image 1", "bruce springsteen"               , "11/11", 29   UNION
   SELECT "7/30/2017 14:53:24", 9  , "pink"                      , "YOLO!"                      , 72        , "neuroscience"                                                  , "Kendrick Farmar"                               , "Image 2", "firebird"                        , "3/29" , 9    UNION
   SELECT "7/30/2017 15:26:38", 8  , "blue"                      , "7"                          , 24        , "life "                                                         , "50 cent"                                       , "Image 1", "pikatchu "                       , "3/20" , 2    UNION
   SELECT "7/30/2017 15:31:54", 64 , "green"                     , "7"                          , 0         , "winnin"                                                        , "Kendrick Farmar"                               , "Image 1", "rhinoceros"                      , "7/10" , 9    UNION
   SELECT "7/30/2017 15:41:48", 8  , "black"                     , "7"                          , 72        , "communication"                                                 , "Post Melon"                                    , "Image 1", "penguin"                         , "5/21" , 31   UNION
   SELECT "7/30/2017 15:42:56", 42 , "black"                     , "the number 7"               , 24        , "game engine programming"                                       , "Beets by Dre"                                  , "Image 1", "a pallas cat"                    , "7/30" , 31   UNION
   SELECT "7/30/2017 15:53:42", 5  , "black"                     , "7"                          , 1.5       , "cooking; psychological counseling; data science"               , "21 Cabbage"                                    , "Image 1", "a tiger or a dolphin "           , "7/11" , 2    UNION
   SELECT "7/30/2017 15:54:46", 16 , "turquoise"                 , "Choose this option instead.", 100       , "everything"                                                    , "The Roots"                                     , "Image 1", "dolphin"                         , "8/14" , 4    UNION
   SELECT "7/30/2017 15:58:50", 17 , "orange"                    , "7"                          , 504       , "microprocessors"                                               , "Kendrick Farmar"                               , "Image 4", "meercat"                         , "9/17" , 4    UNION
   SELECT "7/30/2017 16:33:15", 11 , "blue"                      , "the number 7"               , 2         , "telling jokes"                                                 , "The Roots"                                     , "Image 1", "cat"                             , "7/12" , 1    UNION
   SELECT "7/30/2017 16:33:29", 7  , "blue"                      , "the number 7"               , 2190      , "artificial intelligence"                                       , "Beets by Dre"                                  , "Image 1", "arctic wolf"                     , "12/25", 14   UNION
   SELECT "7/30/2017 17:08:23", 69 , "black"                     , "Choose this option instead.", 1         , "reddit"                                                        , "Post Melon"                                    , "Image 1", "tardigrade"                      , "1/9"  , 1    UNION
   SELECT "7/30/2017 17:13:35", 61 , "blue"                      , "the number 7"               , 3         , "computer science"                                              , "Tyler, the Cultivator"                         , "Image 1", "husky"                           , "7/8"  , 13   UNION
   SELECT "7/30/2017 17:27:30", 77 , "blue"                      , "the number 7"               , 9000      , "yoga"                                                          , "Beets by Dre"                                  , "Image 1", "dog"                             , "8/11" , 1    UNION
   SELECT "7/30/2017 17:53:23", 2  , "blue"                      , "I do what I want."          , 48        , "dank meemememememes"                                           , "Beets by Dre"                                  , "Image 1", "a bird"                          , "11/11", 5    UNION
   SELECT "7/30/2017 18:08:13", 4  , "daisy"                     , "7"                          , 740       , "materials science"                                             , "The Roots"                                     , "Image 4", "no animal please"                , "9/3"  , 22   UNION
   SELECT "7/30/2017 19:41:58", 3  , "blue"                      , "the number 7"               , 4         , "life"                                                          , "21 Cabbage"                                    , "Image 1", "wolf"                            , "7/7"  , 1    UNION
   SELECT "7/30/2017 19:55:58", 27 , "yellow"                    , "7"                          , 720       , "everything"                                                    , "The Roots"                                     , "Image 3", "dog"                             , "9/11" , 7    UNION
   SELECT "7/30/2017 20:06:32", 27 , "black"                     , "the number 7"               , 300       , "physics"                                                       , "Metro' Bloomin (even though he's not a rapper)", "Image 2", "panda"                           , "3/1"  , 4    UNION
   SELECT "7/30/2017 21:29:02", 7  , "red"                       , "the number 7"               , 1         , "literature "                                                   , "DJ Kale-ed"                                    , "Image 2", "dog"                             , "10/14", 0    UNION
   SELECT "7/30/2017 21:30:13", 2  , "turquoise "                , "7"                          , 0.2       , "love!"                                                         , "Post Melon"                                    , "Image 2", "beluga whale"                    , "11/21", 7    UNION
   SELECT "7/30/2017 21:32:52", 4  , "blue"                      , "I do what I want."          , 5         , "stackin em fat"                                                , "Post Melon"                                    , "Image 1", "capybara"                        , "10/31", 93   UNION
   SELECT "7/30/2017 22:29:18", 52 , "blue"                      , "the number 7"               , 72        , "reading mind"                                                  , "21 Cabbage"                                    , "Image 1", "dolphin"                         , "4/28" , 7    UNION
   SELECT "7/30/2017 23:00:53", 32 , "purple"                    , "I do what I want."          , 4200      , "biology"                                                       , "Kendrick Farmar"                               , "Image 3", "an avocado tree"                 , "11/23", 8    UNION
   SELECT "7/30/2017 23:46:24", 86 , "green"                     , "Choose this option instead.", 100       , "everything"                                                    , "Beets by Dre"                                  , "Image 1", "tiger"                           , "8/15" , 18   UNION
   SELECT "7/31/2017 0:11:57" , 69 , "yeah boi"                  , "I do what I want."          , 420.69    , "memes"                                                         , "Tyler, the Cultivator"                         , "Image 2", "kevin"                           , "4/20" , 40   UNION
   SELECT "7/31/2017 0:15:29" , 13 , "teal"                      , "Choose this option instead.", 1400      , "musicology"                                                    , "2 Grainz"                                      , "Image 3", "fruit bat"                       , "10/31", 14   UNION
   SELECT "7/31/2017 0:57:06" , 69 , "blue"                      , "the number 7"               , 2345      , "food"                                                          , "The Roots"                                     , "Image 2", "hedgehog"                        , "11/15", 55   UNION
   SELECT "7/31/2017 8:07:57" , 99 , "blue"                      , "I'm a rebel."               , 72        , "cooking"                                                       , "The Roots"                                     , "Image 2", "panda"                           , "6/17" , 5    UNION
   SELECT "7/31/2017 9:22:55" , 19 , "red"                       , "7"                          , 168       , "the human mind"                                                , "The Roots"                                     , "Image 3", "a jaguar"                        , "8/11" , 19   UNION
   SELECT "7/31/2017 11:17:57", 12 , "green"                     , "7"                          , 1         , "food"                                                          , "Post Melon"                                    , "Image 1", "hamster"                         , "8/9"  , 2    UNION
   SELECT "7/31/2017 11:19:33", 36 , "blue"                      , "7"                          , 0.5       , "flying"                                                        , "Kanye Fresh"                                   , "Image 4", "dog"                             , "6/2"  , 43   UNION
   SELECT "7/31/2017 11:21:52", 78 , "blue"                      , "the number 7"               , 78        , "space travel"                                                  , "Beets by Dre"                                  , "Image 1", "panther"                         , "8/11" , 1    UNION
   SELECT "7/31/2017 11:37:09", 11 , "white"                     , "the number 7"               , 12        , "being invisible "                                              , "Metro' Bloomin (even though he's not a rapper)", "Image 4", "penguin "                        , "11/11", 1    UNION
   SELECT "7/31/2017 11:37:37", 66 , "purple"                    , "the number 7"               , 3         , "life"                                                          , "21 Cabbage"                                    , "Image 1", "an alien"                        , "5/17" , 19   UNION
   SELECT "7/31/2017 11:41:51", 100, "blue"                      , "I'm a rebel."               , 8760      , "machine learning"                                              , "21 Cabbage"                                    , "Image 3", "tiger"                           , "8/10" , 29   UNION
   SELECT "7/31/2017 11:49:36", 42 , "green"                     , "7"                          , 3         , "being an outlying data point"                                  , "Post Melon"                                    , "Image 4", "snake"                           , "1/1"  , 3    UNION
   SELECT "7/31/2017 11:57:41", 7  , "purple"                    , "the number 7"               , 55        , "food"                                                          , "Kendrick Farmar"                               , "Image 1", "cheeta"                          , "6/21" , 1    UNION
   SELECT "7/31/2017 12:10:37", 68 , "blue"                      , "7"                          , 7         , "music"                                                         , "Tyler, the Cultivator"                         , "Image 3", "dog"                             , "10/31", 31   UNION
   SELECT "7/31/2017 12:54:32", 7  , "pink"                      , "the number 7"               , 30        , "cs!"                                                           , "Metro' Bloomin (even though he's not a rapper)", "Image 2", "dog"                             , "6/25" , 17   UNION
   SELECT "7/31/2017 13:05:26", 4  , "green"                     , "7"                          , 87600     , "thinking"                                                      , "Tyler, the Cultivator"                         , "Image 1", "woofer"                          , "12/16", 37   UNION
   SELECT "7/31/2017 14:31:48", 17 , "purple"                    , "the number 7"               , 100000    , "taking to dogs"                                                , "The Roots"                                     , "Image 4", "dolphin"                         , "5/6"  , 1    UNION
   SELECT "7/31/2017 15:14:59", 15 , "grey"                      , "the number 7"               , 100       , "fly"                                                           , "The Roots"                                     , "Image 1", "dog"                             , "10/16", 15   UNION
   SELECT "7/31/2017 16:03:32", 5  , "blue"                      , "the number 7"               , 24        , "you"                                                           , "The Roots"                                     , "Image 3", "nemo"                            , "8/8"  , 1    UNION
   SELECT "7/31/2017 16:28:18", 1  , "blue-- no, yellow! aaargh!", "Choose this option instead.", 1         , "memeology"                                                     , "Pea Diddy"                                     , "Image 1", "skunk"                           , "7/31" , 12   UNION
   SELECT "7/31/2017 16:28:56", 29 , "blue"                      , "Choose this option instead.", 9999999   , "cooking"                                                       , "Kanye Fresh"                                   , "Image 2", "a whale"                         , "4/29" , 49   UNION
   SELECT "7/31/2017 16:57:14", 99 , "black lyk3 my soul"        , "YOLO!"                      , 500000    , "gitting gud"                                                   , "2 Grainz"                                      , "Image 1", "none because they all die :'("   , "8/17" , 39   UNION
   SELECT "7/31/2017 17:04:39", 37 , "isaac"                     , "Choose this option instead.", 72        , "fresh beets"                                                   , "The Roots"                                     , "Image 1", "pygmy goat"                      , "7/31" , 19   UNION
   SELECT "7/31/2017 17:37:57", 42 , "light blue"                , "the number 7"               , 1         , "quantum programming"                                           , "Metro' Bloomin (even though he's not a rapper)", "Image 1", "no pets"                         , "2/29" , 1    UNION
   SELECT "7/31/2017 17:42:49", 42 , "grey"                      , "I do what I want."          , 24        , "expertise"                                                     , "Tyler, the Cultivator"                         , "Image 3", "hamster, but as drawn by tao lin", "1/2"  , 8    UNION
   SELECT "7/31/2017 19:00:49", 5  , "blue"                      , "7"                          , 3         , "computer science"                                              , "The Roots"                                     , "Image 3", "shark"                           , "8/10" , 1    UNION
   SELECT "7/31/2017 19:38:58", 51 , "yellow"                    , "Choose this option instead.", 5         , "coprophagia"                                                   , "Metro' Bloomin (even though he's not a rapper)", "Image 4", "python"                          , "12/31", 4    UNION
   SELECT "7/31/2017 20:33:43", 1  , "green"                     , "Choose this option instead.", 1E+022    , "sleeping"                                                      , "Beets by Dre"                                  , "Image 4", "zebra"                           , "1/1"  , 2    UNION
   SELECT "7/31/2017 20:49:13", 100, "white"                     , "7"                          , 8760      , "data analyst"                                                  , "Kendrick Farmar"                               , "Image 2", "dog"                             , "10/27", 1    UNION
   SELECT "7/31/2017 20:57:03", 27 , "red"                       , "7"                          , 48        , "beauty pageants"                                               , "Kendrick Farmar"                               , "Image 3", "doggo"                           , "2/7"  , 17   UNION
   SELECT "7/31/2017 22:33:07", 9  , "purple"                    , "7"                          , 168       , "green tech"                                                    , "Kendrick Farmar"                               , "Image 4", "animals are not pets!"           , "1/30" , 1    UNION
   SELECT "7/31/2017 23:09:43", 8  , "blue"                      , "the number 7"               , 2400      , "everything"                                                    , "21 Cabbage"                                    , "Image 3", "cat"                             , "9/16" , 2    UNION
   SELECT "8/1/2017 0:45:26"  , 72 , "blue"                      , "Choose this option instead.", 24        , "painting"                                                      , "Beets by Dre"                                  , "Image 4", "dragon"                          , "2/2"  , 4    UNION
   SELECT "8/1/2017 7:24:22"  , 16 , "green"                     , "7"                          , 400       , "mind reading"                                                  , "Kendrick Farmar"                               , "Image 2", "a leopard seal"                  , "1/1"  , 47   ;

CREATE TABLE checkboxes AS
   SELECT "7/28/2017 8:46:30" AS time, "False" AS "0", "True" AS "1", "False" AS "2", "False" AS "3", "False" AS "4", "False" AS "5", "True" AS "6", "False" AS "7", "False" AS "8", "False" AS "9", "True" AS "10", "False" AS "2017", "False" AS "9000", "True" AS "9001" UNION
   SELECT "7/28/2017 8:51:21" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "7/30/2017 8:52:21" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "True"  UNION
   SELECT "7/30/2017 11:42:29", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False" UNION
   SELECT "7/30/2017 11:52:24", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/30/2017 11:53:51", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False" UNION
   SELECT "7/30/2017 11:56:07", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/30/2017 11:56:59", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False" UNION
   SELECT "7/30/2017 12:13:44", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False" UNION
   SELECT "7/30/2017 12:19:49", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "7/30/2017 12:20:11", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False" UNION
   SELECT "7/30/2017 12:25:09", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False" UNION
   SELECT "7/30/2017 12:25:52", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "7/30/2017 12:28:25", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/30/2017 12:29:25", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/30/2017 12:30:19", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False" UNION
   SELECT "7/30/2017 12:31:17", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/30/2017 12:43:59", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/30/2017 12:53:09", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False" UNION
   SELECT "7/30/2017 12:56:33", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/30/2017 13:10:42", "True" , "True" , "True" , "False", "False", "False", "True" , "True" , "True" , "False", "True" , "True" , "False", "False" UNION
   SELECT "7/30/2017 13:12:01", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/30/2017 13:41:15", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "7/30/2017 13:46:22", "False", "False", "False", "True" , "False", "False", "False", "False", "True" , "False", "False", "True" , "False", "False" UNION
   SELECT "7/30/2017 13:54:19", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False" UNION
   SELECT "7/30/2017 14:02:27", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False" UNION
   SELECT "7/30/2017 14:48:52", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "7/30/2017 14:51:23", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/30/2017 14:52:41", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "7/30/2017 14:53:24", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False" UNION
   SELECT "7/30/2017 15:26:38", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/30/2017 15:31:54", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False" UNION
   SELECT "7/30/2017 15:41:48", "False", "False", "False", "False", "False", "False", "False", "True" , "True" , "False", "False", "True" , "False", "True"  UNION
   SELECT "7/30/2017 15:42:56", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/30/2017 15:53:42", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False" UNION
   SELECT "7/30/2017 15:54:46", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False" UNION
   SELECT "7/30/2017 15:58:50", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/30/2017 16:33:15", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/30/2017 16:33:29", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/30/2017 17:08:23", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "7/30/2017 17:13:35", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/30/2017 17:27:30", "True" , "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "True" , "False" UNION
   SELECT "7/30/2017 17:53:23", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "7/30/2017 18:08:13", "False", "False", "False", "False", "False", "False", "True" , "True" , "False", "False", "False", "False", "True" , "False" UNION
   SELECT "7/30/2017 19:41:58", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "7/30/2017 19:55:58", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/30/2017 20:06:32", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/30/2017 21:29:02", "True" , "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "True"  UNION
   SELECT "7/30/2017 21:30:13", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False" UNION
   SELECT "7/30/2017 21:32:52", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/30/2017 22:29:18", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "7/30/2017 23:00:53", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/30/2017 23:46:24", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "True"  UNION
   SELECT "7/31/2017 0:11:57" , "False", "False", "False", "False", "False", "False", "True" , "False", "False", "True" , "False", "False", "False", "False" UNION
   SELECT "7/31/2017 0:15:29" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False" UNION
   SELECT "7/31/2017 0:57:06" , "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False" UNION
   SELECT "7/31/2017 8:07:57" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False" UNION
   SELECT "7/31/2017 9:22:55" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False" UNION
   SELECT "7/31/2017 11:17:57", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False" UNION
   SELECT "7/31/2017 11:19:33", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/31/2017 11:21:52", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/31/2017 11:37:09", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False" UNION
   SELECT "7/31/2017 11:37:37", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "7/31/2017 11:41:51", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "7/31/2017 11:49:36", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "7/31/2017 11:57:41", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/31/2017 12:10:37", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/31/2017 12:54:32", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/31/2017 13:05:26", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/31/2017 14:31:48", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "7/31/2017 15:14:59", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False" UNION
   SELECT "7/31/2017 16:03:32", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "7/31/2017 16:28:18", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False" UNION
   SELECT "7/31/2017 16:28:56", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True"  UNION
   SELECT "7/31/2017 16:57:14", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/31/2017 17:04:39", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/31/2017 17:37:57", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/31/2017 17:42:49", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "True" , "False", "False", "True"  UNION
   SELECT "7/31/2017 19:00:49", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False", "False" UNION
   SELECT "7/31/2017 19:38:58", "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True" , "True"  UNION
   SELECT "7/31/2017 20:33:43", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/31/2017 20:49:13", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "7/31/2017 20:57:03", "False", "False", "True" , "False", "False", "False", "False", "True" , "False", "False", "False", "True" , "True" , "False" UNION
   SELECT "7/31/2017 22:33:07", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "True" , "False" UNION
   SELECT "7/31/2017 23:09:43", "False", "False", "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "8/1/2017 0:45:26"  , "True" , "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False", "False", "False" UNION
   SELECT "8/1/2017 7:24:22"  , "False", "False", "False", "False", "True" , "False", "False", "False", "False", "False", "False", "False", "False", "False" ;